### ISSUE TITLE
Issues about multi_uav ltl motion planning

### ISSUE THREAD

**Issue by jijiking-hh** [vincekurtz/ltl_gcs#1]
Hello author, your  repository is about path planning under the temporal logic constraints of robots. Do you have any recommended papers on multi machine robot systems？Thanks！

**Comment by jijiking-hh** [comment]
![2023-09-07 16-33-20屏幕截图](https://github.com/vincekurtz/ltl_gcs/assets/67863307/86a3f19b-c48a-4f3c-bcab-2fdcf8e66171)
There was no error reported, but there was an error in the above image. I only have Mona that has not been prepared yet. May I ask if the author knows the reason for the above error.

**Comment by jijiking-hh** [comment]
Now that I have prepared Mona, I can basically confirm the three mosek issues. May I know where to put the license specifically

**Comment by aaasss0826** [comment]
May I ask if the author knows the reason for the above error.

**Comment by vincekurtz** [comment]
I suspect the error has to do with Mona not being properly installed. 

As far as MOSEK goes, the `mosek.lic` license file usually goes somewhere like `~/mosek/mosek/lic`. See the [Drake documentation](https://drake.mit.edu/doxygen_cxx/classdrake_1_1solvers_1_1_mosek_solver.html) for more details.

**Comment by zhiqiuyuan** [comment]
> I suspect the error has to do with Mona not being properly installed.
> 
> As far as MOSEK goes, the `mosek.lic` license file usually goes somewhere like `~/mosek/mosek/lic`. See the [Drake documentation](https://drake.mit.edu/doxygen_cxx/classdrake_1_1solvers_1_1_mosek_solver.html) for more details.

Thanks! It solves my problem.
After downloading the source code of mona from https://www.brics.dk/mona/download.html and installing it (following the instructions in the INSTALL file in the repo), and restarting my server, the problem is solved!
